revised for 1.21.1: works with new potion effect, new lowercase forma…
tWizT3ddreaMr/potionarmor pull request #1
Opened 2024-12-07 09:33 UTC by tonyjamesstark

…t for config effect names, added linting with spotless

2025-03-23 18:09 UTC, tWizT3ddreaMr commented
I will merge it but what is the high change count
It looks like the changes are basically the same

2025-03-23 19:38 UTC, tonyjamesstark commented
I used a linter to reformat(jdtls).... if you prefer I can keep the previous and just commit the relevant changes

2025-03-23 21:03 UTC, tWizT3ddreaMr commented
That's fine, however you didn't really change much after review
If you change a lot I would be open to add you to the author list in the plugin.yml, but for now, as this is a public plugin I would rather not to yet

2025-03-26 00:40 UTC, tWizT3ddreaMr requested changes
plugin.yml
First off, I am the author. I like you and respect you, if you changed more I may be more willing.
Second I think for multiple would have been authors: just a fyi

2025-04-01 00:05 UTC, merged